### ISSUE TITLE
add reade me  

### ISSUE THREAD

**Issue by nathanmcunha** [felipeprintes/TOPSIS#2]
add READE ME

**Comment by felipeprintes** [comment]
### **TOPSIS**
Topsis é um é uma técnica que tem como objetivo auxiliar as pessoas em suas tomadas de decisão.

### **Por que utilizar?**
Com os pesos passados pelo gestor da equipe, ou especialista do assunto, pode-se chegar a melhor decisão a ser tomada

### Ferramentas
Para criação do algoritmo TOPSIS, foi utilizado ferramentas open source
- Python 3
- Flask
- HTML
- CSS
